// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package gwp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PoolClosed-1]
	_ = x[InvalidMaxWorker-2]
	_ = x[InvalidWarmWorkers-3]
	_ = x[PoolJobQueueFull-4]
	_ = x[InsufficientCapacityForBatchJob-5]
}

const _ErrorCode_name = "PoolClosedInvalidMaxWorkerInvalidWarmWorkersPoolJobQueueFullInsufficientCapacityForBatchJob"

var _ErrorCode_index = [...]uint8{0, 10, 26, 44, 60, 91}

func (i ErrorCode) String() string {
	i -= 1
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
