// Code generated by "stringer -type=Status"; DO NOT EDIT.

package gwp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Enqueued-0]
	_ = x[Processing-1]
	_ = x[Success-2]
	_ = x[Cancelled-3]
	_ = x[Failed-4]
	_ = x[Rejected-5]
}

const _Status_name = "EnqueuedProcessingSuccessCancelledFailedRejected"

var _Status_index = [...]uint8{0, 8, 18, 25, 34, 40, 48}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
